<?php

namespace Database\Seeders;

use App\Models\ProjectImage;
use Illuminate\Database\Eloquent\Factories\Sequence;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProjectImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('project_images')->insert([
            [
                'project_id' => '1',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/eksterior.jpg',
                'description' => 'Eksterior rumah dengan gaya modern',
                'style_id' => '2',
                'room_id' => '8',
                'budget_id' => '3',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '1',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017727/homelize/room/ruang-keluarga.jpg',
                'description' => 'ruang keluarga dengan gaya rumah minimalis',
                'style_id' => '1',
                'room_id' => '3',
                'budget_id' => '1',
                'minimum_budget' => '3000000',
                'maximum_budget' => '4000000',    
            ],
            [
                'project_id' => '1',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017727/homelize/room/dapur.jpg',
                'description' => 'ruang dapur dengan gaya modern',
                'style_id' => '2',
                'room_id' => '1',
                'budget_id' => '2',
                'minimum_budget' => '300000000',
                'maximum_budget' => '400000000',    
            ],
            [
                'project_id' => '1',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017726/homelize/room/ruang-makan.jpg',
                'description' => 'ruang makan dengan gaya modern',
                'style_id' => '4',
                'room_id' => '2',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '2',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1642068551/Example/exterior-elevation-pratibha-and-associates-img_c5111a860ce65dd5_4-9714-1-b0c36f1.jpg',
                'description' => 'Eksterior rumah dengan gaya modern',
                'style_id' => '2',
                'room_id' => '8',
                'budget_id' => '3',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '2',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kolam-renang.jpg',
                'description' => 'kolam berenang dengan gaya modern',
                'style_id' => '2',
                'room_id' => '10',
                'budget_id' => '2',
                'minimum_budget' => '10000000000',
                'maximum_budget' => '20000000000',    
            ],
            [
                'project_id' => '2',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kamar-tidur.jpg',
                'description' => 'kamar tidur dengan gaya modern',
                'style_id' => '6',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '3',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017727/homelize/room/dapur.jpg',
                'description' => 'dapur dengan gaya minimalis',
                'style_id' => '1',
                'room_id' => '1',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '3',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kamar-mandi.jpg',
                'description' => 'kamar mandi dengan gaya minimalis',
                'style_id' => '1',
                'room_id' => '5',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '4',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kamar-tidur.jpg',
                'description' => 'kamar tidur dengan gaya modern',
                'style_id' => '6',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '4',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kamar-mandi.jpg',
                'description' => 'kamar mandi dengan gaya skandinavian',
                'style_id' => '7',
                'room_id' => '5',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '5',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1642068650/Example/Desain-Interior-Kamar-Tidur-Utama.jpg',
                'description' => 'kamar tidur dengan gaya modern',
                'style_id' => '6',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '5',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017724/homelize/room/kamar-mandi.jpg',
                'description' => 'kamar mandi dengan gaya kontemporer',
                'style_id' => '4',
                'room_id' => '5',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '5',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1639017725/homelize/room/taman.jpg',
                'description' => 'taman dengan gaya industrial',
                'style_id' => '9',
                'room_id' => '9',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',    
            ],
            [
                'project_id' => '6',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551284/homelize/room/eksterior-minimalis-1.jpg',
                'description' => 'eksterior rumah minimalis 2 lantai',
                'style_id' => '1',
                'room_id' => '8',
                'budget_id' => '1',
                'minimum_budget' => '50000000',
                'maximum_budget' => '100000000',    
            ],
            [
                'project_id' => '6',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551284/homelize/room/kamr-minimalis-1.jpg',
                'description' => 'kamar tidur dengan 1 tempat tidur minimalis',
                'style_id' => '1',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '30000000',
                'maximum_budget' => '40000000',    
            ],
            [
                'project_id' => '6',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551284/homelize/room/r-keluarga-minimalis-1.jpg',
                'description' => 'ruang keluarga dengan gaya minimalis',
                'style_id' => '1',
                'room_id' => '3',
                'budget_id' => '1',
                'minimum_budget' => '60000000',
                'maximum_budget' => '70000000',    
            ],
            [
                'project_id' => '6',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551284/homelize/room/r-makan-minimalis-1.jpg',
                'description' => 'ruang keluarga dengan nuansa nyaman dan sederhana',
                'style_id' => '1',
                'room_id' => '2',
                'budget_id' => '1',
                'minimum_budget' => '40000000',
                'maximum_budget' => '50000000',    
            ],
            [
                'project_id' => '7',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551597/homelize/room/ekterior-modern-1.jpg',
                'description' => 'eksterior rumah modern',
                'style_id' => '2',
                'room_id' => '8',
                'budget_id' => '2',
                'minimum_budget' => '150000000',
                'maximum_budget' => '200000000',    
            ],
            [
                'project_id' => '7',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551597/homelize/room/kamar-modern-1.jpg',
                'description' => 'kamar dengan satu tempat tidur dengan nuansa mewah',
                'style_id' => '2',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '110000000',
                'maximum_budget' => '120000000',    
            ],
            [
                'project_id' => '7',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551597/homelize/room/r-keluarga-modern-1.jpg',
                'description' => 'ruang keluarga dengan nuansa elegan dan mewah',
                'style_id' => '2',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '140000000',
                'maximum_budget' => '150000000',    
            ],
            [
                'project_id' => '8',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551927/homelize/room/ekterior-klasik-1.jpg',
                'description' => 'desain ekterior rumah klasik',
                'style_id' => '3',
                'room_id' => '8',
                'budget_id' => '2',
                'minimum_budget' => '200000000',
                'maximum_budget' => '300000000',    
            ],
            [
                'project_id' => '8',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551927/homelize/room/k-tidur-klasik-1.jpg',
                'description' => 'kamar tidur dengan desain klasik',
                'style_id' => '3',
                'room_id' => '4',
                'budget_id' => '2',
                'minimum_budget' => '140000000',
                'maximum_budget' => '150000000',    
            ],
            [
                'project_id' => '8',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643551927/homelize/room/k-mandi-klasik-1.jpg',
                'description' => 'kamar mandi dengan gaya klasik',
                'style_id' => '3',
                'room_id' => '5',
                'budget_id' => '2',
                'minimum_budget' => '140000000',
                'maximum_budget' => '150000000',    
            ],
            [
                'project_id' => '9',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643552858/homelize/room/k-tidur-minimalis-2.jpg',
                'description' => 'kamar tidur gaya minimalis',
                'style_id' => '1',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',    
            ],
            [
                'project_id' => '9',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643552858/homelize/room/k-tidur-minmalis-2.jpg',
                'description' => 'kamar tidur gaya minimalis',
                'style_id' => '1',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',      
            ],
            [
                'project_id' => '9',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643552858/homelize/room/k-tidur-minamilisss-2.jpg',
                'description' => 'kamar tidur gaya minimalis',
                'style_id' => '1',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',      
            ],
            [
                'project_id' => '9',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643552857/homelize/room/r-makan-minimalis-2.jpg',
                'description' => 'ruang makan minimalis',
                'style_id' => '1',
                'room_id' => '2',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',    
            ],
            [
                'project_id' => '10',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553150/homelize/room/dapur-modern-2.jpg',
                'description' => 'desain dapur modern',
                'style_id' => '2',
                'room_id' => '1',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '80000000',    
            ],
            [
                'project_id' => '10',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553150/homelize/room/dapur-modernn-3.jpg',
                'description' => 'desain dapur modern',
                'style_id' => '2',
                'room_id' => '1',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '80000000',    
            ],
            [
                'project_id' => '10',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553149/homelize/room/dapur-moderrnn-3.jpg',
                'description' => 'desain dapur modern',
                'style_id' => '2',
                'room_id' => '1',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '80000000',    
            ],
            [
                'project_id' => '10',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553149/homelize/room/dapur-modernn-2.jpg',
                'description' => 'desain dapur modern',
                'style_id' => '2',
                'room_id' => '1',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '80000000',   
            ],
            [
                'project_id' => '11',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553563/homelize/room/ekterior-skandinav-1.jpg',
                'description' => 'desain rumah ekterior skandinavian',
                'style_id' => '7',
                'room_id' => '8',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '90000000',   
            ],
            [
                'project_id' => '11',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553563/homelize/room/r-makan-skandinva-1.jpg',
                'description' => 'ruang makan dengan gaya skandinavian',
                'style_id' => '7',
                'room_id' => '2',
                'budget_id' => '1',
                'minimum_budget' => '50000000',
                'maximum_budget' => '60000000',   
            ],
            [
                'project_id' => '11',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553563/homelize/room/r-keluarga-skandinavian.jpg',
                'description' => 'ruang keluarga dengan gaya skandinavian',
                'style_id' => '7',
                'room_id' => '3',
                'budget_id' => '1',
                'minimum_budget' => '70000000',
                'maximum_budget' => '80000000',   
            ],
            [
                'project_id' => '11',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643553563/homelize/room/k-tidur-skandinav-1.jpg',
                'description' => 'kamar tidur dengan gaya skandinavian',
                'style_id' => '7',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '50000000',
                'maximum_budget' => '60000000',   
            ],
            [
                'project_id' => '12',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643554050/homelize/room/ekterior-mediterania-2.jpg',
                'description' => 'rumah dua lantai dengan gaya mediterania',
                'style_id' => '8',
                'room_id' => '8',
                'budget_id' => '2',
                'minimum_budget' => '500000000',
                'maximum_budget' => '600000000',   
            ],
            [
                'project_id' => '12',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643554050/homelize/room/r-keluarga-mediterania-3.jpg',
                'description' => 'ruang keluarga dengan gaya mediterania',
                'style_id' => '8',
                'room_id' => '3',
                'budget_id' => '1',
                'minimum_budget' => '60000000',
                'maximum_budget' => '70000000',   
            ],
            [
                'project_id' => '12',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643554049/homelize/room/r-makan-medierania.jpg',
                'description' => 'ruang makan dengan gaya mediterania',
                'style_id' => '8',
                'room_id' => '2',
                'budget_id' => '1',
                'minimum_budget' => '75000000',
                'maximum_budget' => '80000000',   
            ],
            [
                'project_id' => '12',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643554050/homelize/room/kamar-tidur-mediterania-2.jpg',
                'description' => 'kamar tidur dengan gaya mediterania',
                'style_id' => '8',
                'room_id' => '4',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',   
            ],
            [
                'project_id' => '12',
                'image_path' => 'https://res.cloudinary.com/dwrorg2la/image/upload/v1643554050/homelize/room/taman-mediterania.jpg',
                'description' => 'taman dengan gaya mediterania',
                'style_id' => '8',
                'room_id' => '9',
                'budget_id' => '1',
                'minimum_budget' => '80000000',
                'maximum_budget' => '90000000',   
            ],
        ]);
    }
}
